### PR TITLE
Use Drifter for vagrant provisioning.

### PR DESCRIPTION
**Pull request by bellisk**

### CODE REVIEW

**Comment by lsmith77** [comment]
I tried to set this up and got:
```
Fatal error: Uncaught exception 'Exception' with message 'Cannot find the PHP APC module. Please install or enable it for this app to work' in /vagrant/web/index.php:12 Stack trace: #0 {main} thrown in /vagrant/web/index.php on line 12
```

**Comment by bellisk** [comment]
@lsmith77 Can you try it again now? I changed the task that installs php5-acpu to restart apache afterwards, so it should work. (You will see other errors on the presence.lo page but those are expected because the settings are not filled in.)

**Comment by lsmith77** [comment]
looks better .. I guess now I just miss some config

```Fatal error: Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'Reference "***********.apps.googleusercontent.com" does not exist at line 0.' in /vagrant/vendor/symfony/yaml/Symfony/Component/Yaml/Parser.php:384 Stack trace: #0 /vagrant/vendor/symfony/yaml/Symfony/Component/Yaml/Parser.php(189): Symfony\Component\Yaml\Parser->parseValue('************.ap...', false, false) #1 /vagrant/vendor/symfony/yaml/Symfony/Component/Yaml/Parser.php(183): Symfony\Component\Yaml\Parser->parse('key: **********...', false, false) #2 /vagrant/web/index.php(20): Symfony\Component\Yaml\Parser->parse('timezone: Europ...') #3 {main} thrown in /vagrant/vendor/symfony/yaml/Symfony/Component/Yaml/Parser.php on line 384```

**Comment by bellisk** [comment]
Yup, that stuff needs to be filled in when you have set up a project on the Google developer console.

**Pull request merged**
